// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wwiMiRQOSz6NiN1wJNkgV6fS0FX6RQs',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'ssg-digi-dev',
    authDomain: 'ssg-digi-dev.firebaseapp.com',
    storageBucket: 'ssg-digi-dev.appspot.com',
    measurementId: 'G-8HWE9GSH4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDQMojCQY_kGJBrZMf754QAKYENb5Xgk',
    appId: '1:309202182787:android:d948cf11b85e711ae8b1b6',
    messagingSenderId: '309202182787',
    projectId: 'ssg-digi',
    storageBucket: 'ssg-digi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wwiMiRQOSz6NiN1wJNkgV6fS0FX6RQs',
    appId: '1:448618578101:ios:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'ssg-digi-dev',
    authDomain: 'ssg-digi-dev.firebaseapp.com',
    storageBucket: 'ssg-digi-dev.appspot.com',
    iosClientId: '448618578101-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ssgDigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wwiMiRQOSz6NiN1wJNkgV6fS0FX6RQs',
    appId: '1:448618578101:ios:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'ssg-digi-dev',
    authDomain: 'ssg-digi-dev.firebaseapp.com',
    storageBucket: 'ssg-digi-dev.appspot.com',
    iosClientId: '448618578101-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ssgDigi',
  );
}